[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/rpc"
  to = "/.netlify/functions/rpc"
  status = 200
  force = true

[[redirects]]
  from = "/api/dexscreener/*"
  to = "https://api.dexscreener.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/gecko/*"
  to = "https://api.geckoterminal.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
